[package]
name = "egui_commonmark"
authors = ["Erlend Walstad"]
version = "0.7.4"
edition = "2021"
description = "Commonmark viewer for egui"
keywords = ["commonmark", "egui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lampsitter/egui_commonmark"
documentation = "https://docs.rs/egui_commonmark"
include = ["src/*.rs", "LICENSE-MIT", "LICENSE-APACHE", "Cargo.toml"]

[dependencies]
egui = { git = "https://github.com/emilk/egui", rev = "d949eaf" }
pulldown-cmark = { version = "0.9.3", default-features = false }
egui_extras = { git = "https://github.com/emilk/egui", rev = "d949eaf" }

syntect = { version = "5.0.0", optional = true, default-features = false, features = [
    "default-fancy",
] }

document-features = { version = "0.2", optional = true }

[features]
default = ["load-images"]
## Syntax highlighting for code blocks
syntax_highlighting = ["syntect"]

load-images = ["egui_extras/image", "egui_extras/file", "image/png"]

## Support loading svg images
svg = ["egui_extras/svg"]

## Images with urls will be downloaded and displayed
fetch = ["egui_extras/http", "image/jpeg"]

[dev-dependencies]
eframe = { git = "https://github.com/emilk/egui", rev = "d949eaf" }
image = { version = "0.24", default-features = false, features = ["png"] }

[package.metadata.docs.rs]
# docs.rs build can fail with the fetch feature enabled
features = ["syntax_highlighting", "svg", "document-features"]
