[package]
name = "egui_commonmark"
authors = ["Erlend Walstad"]
version = "0.1.0"
edition = "2021"

[dependencies]
# Depend on master until next release
egui = { git = "https://github.com/emilk/egui", rev = "defc400c21aaf3fc61f4a7530f13fdbe5991fcc1" }
pulldown-cmark = "0.9.1"
resvg = { version = "0.20.0", optional = true }
usvg = { version = "0.20.0", optional = true }
tiny-skia = { version = "0.6.3", optional = true }
image = { version = "0.24", default-features = false, features = ["png"]}

syntect = { version = "4.6.0", optional = true, default-features = false, features = ["default-fancy"]  }

[features]
default = ["svg", "syntax_highlighting"]

# Syntax highlighting or code blocks
syntax_highlighting = ["syntect"]
# Support loading svg images
svg = ["resvg", "usvg", "tiny-skia"]
