name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check
    - name: Check all features
      run: cargo check --all-features
    - name: Tests
      run: cargo test --all-features
    - name: Clippy
      run: cargo clippy -- -Dwarnings
