name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy -- -Dwarnings
    - name: Check all features
      run: cargo check --all-features
    - name: Cargo fmt
      run: cargo fmt --check -q
